### ISSUE TITLE
Get Meeting Time for Localization

### ISSUE THREAD

**Issue by emmaskychuks** [iscumd/Yeti#11]

**Comment by bddidona** [comment]
@emmaskychuks Has this happened yet? If our PDR will be happening mid-October we need to have a solid plan by then at least, if our code/feature freeze is late-November we have only about a month to have this finished

**Comment by emmaskychuks** [comment]
@airfield20 Do you have an update for this?

**Comment by emmaskychuks** [comment]
I think, for now, meetings are on Wednesdays.

**Comment by EpicWolverine** [comment]
Meetings are Wednesdays 2-4pm
