### ISSUE TITLE
Research on snow detection for Yeti

### ISSUE THREAD

**Issue by emmaskychuks** [iscumd/Yeti#13]

**Comment by bddidona** [comment]
This might be possible through comparing the depth of the pavement and snow to determine approximate snow cover and depth

**Comment by mikebowyer** [comment]
just curios what is the sensor set for yeti this year? This will limit approaches, that is why I am asking.

**Comment by emmaskychuks** [comment]
We plan on using both camera and lidar for vision this year.

**Comment by bddidona** [comment]
For a single camera this is working, we will now need to look into dual camera/3d space
