### ISSUE TITLE
Modify Camera Mount

### ISSUE THREAD

**Issue by airfield20** [iscumd/Yeti#17]

**Comment by Sriracus615** [comment]
Finished camera clamp design in SolidWorks; part file ready. A .stl needs to be created of it for 3D printing.

**Comment by Sriracus615** [comment]
Camera mount has been successfully 3D printed. It snaps fairly well onto the camera so now the next step is drilling holes onto the L-channel and actually mounting the camera to ensure the mount holds it in place. M5 bolts will be used for mounting the camera mount.

**Comment by EpicWolverine** [comment]
This mount is on the robot now, right? Is this issue done or are there tasks left?

**Comment by airfield20** [comment]
It's done
