### ISSUE TITLE
Setup Zotac machine and run inside yeti

### ISSUE THREAD

**Issue by airfield20** [iscumd/Yeti#32]

**Comment by EpicWolverine** [comment]
I got the Zotac set up as the ROS master on 192.168.0.102. It runs everything but the GPIO node now. I reconfigured the Pi to connect to it as well. It’s running yeti_snowplow/start_yeti.launch with a few updates. See 3d160d245c565a8cacc9f1b16a964e9715761647

The adhesive holding the computer to the door didn't hold. We need to reapply it but rough up the board first or find another attachment solution.

**Comment by EpicWolverine** [comment]
Done
