### ISSUE TITLE
Backup YetiPi

### ISSUE THREAD

**Issue by EpicWolverine** [iscumd/Yeti#34]
Now that Yeti's internal Pi has been updated with changes incompatible with the previous image, a new image should be made.

AC:
* Make an image of the Pi's SD card.
    * It would be nice if this was only as big as it needs to be instead of the full size of the card
* Upload the image to Drive **alongside** the previous image.
* Notify #team_yeti-x_asc and this issue

**Comment by srawa** [comment]
For my class, I provide RasPi images with ROS pre-installed.

Would that be of interest?  They are available on my website under
Teaching: sar-lab.net

(Mobile)

**Comment by EpicWolverine** [comment]
We already have the Pi set up (thanks @dcutting133). I don't know if it's the best way (he had to jump through some hoops) but it works. This task was just creating a backup so we can just image a new SD card if the current one fails. Your images would be helpful for other teams though (@CrisAdam was recently asking about one).
