### ISSUE TITLE
Learn how to create a robot in Gazebo (Tutorial)

### ISSUE THREAD

**Issue by emmaskychuks** [iscumd/Yeti#9]

**Comment by airfield20** [comment]
@EpicWolverine Here is the tutorial for creating models in gazebo http://gazebosim.org/tutorials?cat=guided_b&tut=guided_b3

**Comment by airfield20** [comment]
@EpicWolverine Also check out this tutorial on how to build a world. We can probably construct the snowplow scene this way http://gazebosim.org/tutorials?tut=build_world&cat=build_world
